package com.telefonica.centroseducativos.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Usuario service. Represents a row in the &quot;CentrosEducativos_Usuario&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.telefonica.centroseducativos.model.impl.UsuarioModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.telefonica.centroseducativos.model.impl.UsuarioImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Usuario
 * @see com.telefonica.centroseducativos.model.impl.UsuarioImpl
 * @see com.telefonica.centroseducativos.model.impl.UsuarioModelImpl
 * @generated
 */
public interface UsuarioModel extends BaseModel<Usuario> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a usuario model instance should use the {@link Usuario} interface instead.
     */

    /**
     * Returns the primary key of this usuario.
     *
     * @return the primary key of this usuario
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this usuario.
     *
     * @param primaryKey the primary key of this usuario
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the usuario ID of this usuario.
     *
     * @return the usuario ID of this usuario
     */
    public long getUsuarioId();

    /**
     * Sets the usuario ID of this usuario.
     *
     * @param usuarioId the usuario ID of this usuario
     */
    public void setUsuarioId(long usuarioId);

    /**
     * Returns the curso academico of this usuario.
     *
     * @return the curso academico of this usuario
     */
    @AutoEscape
    public String getCursoAcademico();

    /**
     * Sets the curso academico of this usuario.
     *
     * @param cursoAcademico the curso academico of this usuario
     */
    public void setCursoAcademico(String cursoAcademico);

    /**
     * Returns the ha contestado la encuesta of this usuario.
     *
     * @return the ha contestado la encuesta of this usuario
     */
    public boolean getHaContestadoLaEncuesta();

    /**
     * Returns <code>true</code> if this usuario is ha contestado la encuesta.
     *
     * @return <code>true</code> if this usuario is ha contestado la encuesta; <code>false</code> otherwise
     */
    public boolean isHaContestadoLaEncuesta();

    /**
     * Sets whether this usuario is ha contestado la encuesta.
     *
     * @param haContestadoLaEncuesta the ha contestado la encuesta of this usuario
     */
    public void setHaContestadoLaEncuesta(boolean haContestadoLaEncuesta);

    /**
     * Returns the idrol of this usuario.
     *
     * @return the idrol of this usuario
     */
    public int getIdrol();

    /**
     * Sets the idrol of this usuario.
     *
     * @param idrol the idrol of this usuario
     */
    public void setIdrol(int idrol);

    /**
     * Returns the idce of this usuario.
     *
     * @return the idce of this usuario
     */
    public int getIdce();

    /**
     * Sets the idce of this usuario.
     *
     * @param idce the idce of this usuario
     */
    public void setIdce(int idce);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.telefonica.centroseducativos.model.Usuario usuario);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.telefonica.centroseducativos.model.Usuario> toCacheModel();

    @Override
    public com.telefonica.centroseducativos.model.Usuario toEscapedModel();

    @Override
    public com.telefonica.centroseducativos.model.Usuario toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
