package com.telefonica.centroseducativos.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import com.telefonica.centroseducativos.model.ComunidadAutonoma;
import com.telefonica.centroseducativos.model.ComunidadAutonomaModel;
import com.telefonica.centroseducativos.model.ComunidadAutonomaSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the ComunidadAutonoma service. Represents a row in the &quot;CentrosEducativos_ComunidadAutonoma&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.telefonica.centroseducativos.model.ComunidadAutonomaModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ComunidadAutonomaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ComunidadAutonomaImpl
 * @see com.telefonica.centroseducativos.model.ComunidadAutonoma
 * @see com.telefonica.centroseducativos.model.ComunidadAutonomaModel
 * @generated
 */
@JSON(strict = true)
public class ComunidadAutonomaModelImpl extends BaseModelImpl<ComunidadAutonoma>
    implements ComunidadAutonomaModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a comunidad autonoma model instance should use the {@link com.telefonica.centroseducativos.model.ComunidadAutonoma} interface instead.
     */
    public static final String TABLE_NAME = "CentrosEducativos_ComunidadAutonoma";
    public static final Object[][] TABLE_COLUMNS = {
            { "idca", Types.INTEGER },
            { "nombrecomunidad", Types.VARCHAR },
            { "idpais", Types.INTEGER }
        };
    public static final String TABLE_SQL_CREATE = "create table CentrosEducativos_ComunidadAutonoma (idca INTEGER not null primary key,nombrecomunidad VARCHAR(75) null,idpais INTEGER)";
    public static final String TABLE_SQL_DROP = "drop table CentrosEducativos_ComunidadAutonoma";
    public static final String ORDER_BY_JPQL = " ORDER BY comunidadAutonoma.idca ASC";
    public static final String ORDER_BY_SQL = " ORDER BY CentrosEducativos_ComunidadAutonoma.idca ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.telefonica.centroseducativos.model.ComunidadAutonoma"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.telefonica.centroseducativos.model.ComunidadAutonoma"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = false;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.telefonica.centroseducativos.model.ComunidadAutonoma"));
    private static ClassLoader _classLoader = ComunidadAutonoma.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            ComunidadAutonoma.class
        };
    private int _idca;
    private String _nombrecomunidad;
    private int _idpais;
    private ComunidadAutonoma _escapedModel;

    public ComunidadAutonomaModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static ComunidadAutonoma toModel(ComunidadAutonomaSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        ComunidadAutonoma model = new ComunidadAutonomaImpl();

        model.setIdca(soapModel.getIdca());
        model.setNombrecomunidad(soapModel.getNombrecomunidad());
        model.setIdpais(soapModel.getIdpais());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<ComunidadAutonoma> toModels(
        ComunidadAutonomaSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<ComunidadAutonoma> models = new ArrayList<ComunidadAutonoma>(soapModels.length);

        for (ComunidadAutonomaSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public int getPrimaryKey() {
        return _idca;
    }

    @Override
    public void setPrimaryKey(int primaryKey) {
        setIdca(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _idca;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Integer) primaryKeyObj).intValue());
    }

    @Override
    public Class<?> getModelClass() {
        return ComunidadAutonoma.class;
    }

    @Override
    public String getModelClassName() {
        return ComunidadAutonoma.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("idca", getIdca());
        attributes.put("nombrecomunidad", getNombrecomunidad());
        attributes.put("idpais", getIdpais());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Integer idca = (Integer) attributes.get("idca");

        if (idca != null) {
            setIdca(idca);
        }

        String nombrecomunidad = (String) attributes.get("nombrecomunidad");

        if (nombrecomunidad != null) {
            setNombrecomunidad(nombrecomunidad);
        }

        Integer idpais = (Integer) attributes.get("idpais");

        if (idpais != null) {
            setIdpais(idpais);
        }
    }

    @JSON
    @Override
    public int getIdca() {
        return _idca;
    }

    @Override
    public void setIdca(int idca) {
        _idca = idca;
    }

    @JSON
    @Override
    public String getNombrecomunidad() {
        if (_nombrecomunidad == null) {
            return StringPool.BLANK;
        } else {
            return _nombrecomunidad;
        }
    }

    @Override
    public void setNombrecomunidad(String nombrecomunidad) {
        _nombrecomunidad = nombrecomunidad;
    }

    @JSON
    @Override
    public int getIdpais() {
        return _idpais;
    }

    @Override
    public void setIdpais(int idpais) {
        _idpais = idpais;
    }

    @Override
    public ComunidadAutonoma toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (ComunidadAutonoma) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        ComunidadAutonomaImpl comunidadAutonomaImpl = new ComunidadAutonomaImpl();

        comunidadAutonomaImpl.setIdca(getIdca());
        comunidadAutonomaImpl.setNombrecomunidad(getNombrecomunidad());
        comunidadAutonomaImpl.setIdpais(getIdpais());

        comunidadAutonomaImpl.resetOriginalValues();

        return comunidadAutonomaImpl;
    }

    @Override
    public int compareTo(ComunidadAutonoma comunidadAutonoma) {
        int primaryKey = comunidadAutonoma.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof ComunidadAutonoma)) {
            return false;
        }

        ComunidadAutonoma comunidadAutonoma = (ComunidadAutonoma) obj;

        int primaryKey = comunidadAutonoma.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
    }

    @Override
    public CacheModel<ComunidadAutonoma> toCacheModel() {
        ComunidadAutonomaCacheModel comunidadAutonomaCacheModel = new ComunidadAutonomaCacheModel();

        comunidadAutonomaCacheModel.idca = getIdca();

        comunidadAutonomaCacheModel.nombrecomunidad = getNombrecomunidad();

        String nombrecomunidad = comunidadAutonomaCacheModel.nombrecomunidad;

        if ((nombrecomunidad != null) && (nombrecomunidad.length() == 0)) {
            comunidadAutonomaCacheModel.nombrecomunidad = null;
        }

        comunidadAutonomaCacheModel.idpais = getIdpais();

        return comunidadAutonomaCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(7);

        sb.append("{idca=");
        sb.append(getIdca());
        sb.append(", nombrecomunidad=");
        sb.append(getNombrecomunidad());
        sb.append(", idpais=");
        sb.append(getIdpais());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(13);

        sb.append("<model><model-name>");
        sb.append("com.telefonica.centroseducativos.model.ComunidadAutonoma");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>idca</column-name><column-value><![CDATA[");
        sb.append(getIdca());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>nombrecomunidad</column-name><column-value><![CDATA[");
        sb.append(getNombrecomunidad());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>idpais</column-name><column-value><![CDATA[");
        sb.append(getIdpais());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
