package com.telefonica.centroseducativos.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.telefonica.centroseducativos.model.Pais;
import com.telefonica.centroseducativos.service.PaisLocalServiceUtil;

/**
 * The extended model base implementation for the Pais service. Represents a row in the &quot;CentrosEducativos_Pais&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PaisImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PaisImpl
 * @see com.telefonica.centroseducativos.model.Pais
 * @generated
 */
public abstract class PaisBaseImpl extends PaisModelImpl implements Pais {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a pais model instance should use the {@link Pais} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            PaisLocalServiceUtil.addPais(this);
        } else {
            PaisLocalServiceUtil.updatePais(this);
        }
    }
}
