package com.telefonica.centroseducativos.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import com.telefonica.centroseducativos.model.RolUsuario;
import com.telefonica.centroseducativos.model.RolUsuarioModel;
import com.telefonica.centroseducativos.model.RolUsuarioSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the RolUsuario service. Represents a row in the &quot;CentrosEducativos_RolUsuario&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.telefonica.centroseducativos.model.RolUsuarioModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RolUsuarioImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RolUsuarioImpl
 * @see com.telefonica.centroseducativos.model.RolUsuario
 * @see com.telefonica.centroseducativos.model.RolUsuarioModel
 * @generated
 */
@JSON(strict = true)
public class RolUsuarioModelImpl extends BaseModelImpl<RolUsuario>
    implements RolUsuarioModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a rol usuario model instance should use the {@link com.telefonica.centroseducativos.model.RolUsuario} interface instead.
     */
    public static final String TABLE_NAME = "CentrosEducativos_RolUsuario";
    public static final Object[][] TABLE_COLUMNS = {
            { "idrol", Types.INTEGER },
            { "nombrerol", Types.VARCHAR }
        };
    public static final String TABLE_SQL_CREATE = "create table CentrosEducativos_RolUsuario (idrol INTEGER not null primary key,nombrerol VARCHAR(75) null)";
    public static final String TABLE_SQL_DROP = "drop table CentrosEducativos_RolUsuario";
    public static final String ORDER_BY_JPQL = " ORDER BY rolUsuario.idrol ASC";
    public static final String ORDER_BY_SQL = " ORDER BY CentrosEducativos_RolUsuario.idrol ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.telefonica.centroseducativos.model.RolUsuario"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.telefonica.centroseducativos.model.RolUsuario"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = false;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.telefonica.centroseducativos.model.RolUsuario"));
    private static ClassLoader _classLoader = RolUsuario.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            RolUsuario.class
        };
    private int _idrol;
    private String _nombrerol;
    private RolUsuario _escapedModel;

    public RolUsuarioModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static RolUsuario toModel(RolUsuarioSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        RolUsuario model = new RolUsuarioImpl();

        model.setIdrol(soapModel.getIdrol());
        model.setNombrerol(soapModel.getNombrerol());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<RolUsuario> toModels(RolUsuarioSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<RolUsuario> models = new ArrayList<RolUsuario>(soapModels.length);

        for (RolUsuarioSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public int getPrimaryKey() {
        return _idrol;
    }

    @Override
    public void setPrimaryKey(int primaryKey) {
        setIdrol(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _idrol;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Integer) primaryKeyObj).intValue());
    }

    @Override
    public Class<?> getModelClass() {
        return RolUsuario.class;
    }

    @Override
    public String getModelClassName() {
        return RolUsuario.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("idrol", getIdrol());
        attributes.put("nombrerol", getNombrerol());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Integer idrol = (Integer) attributes.get("idrol");

        if (idrol != null) {
            setIdrol(idrol);
        }

        String nombrerol = (String) attributes.get("nombrerol");

        if (nombrerol != null) {
            setNombrerol(nombrerol);
        }
    }

    @JSON
    @Override
    public int getIdrol() {
        return _idrol;
    }

    @Override
    public void setIdrol(int idrol) {
        _idrol = idrol;
    }

    @JSON
    @Override
    public String getNombrerol() {
        if (_nombrerol == null) {
            return StringPool.BLANK;
        } else {
            return _nombrerol;
        }
    }

    @Override
    public void setNombrerol(String nombrerol) {
        _nombrerol = nombrerol;
    }

    @Override
    public RolUsuario toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (RolUsuario) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        RolUsuarioImpl rolUsuarioImpl = new RolUsuarioImpl();

        rolUsuarioImpl.setIdrol(getIdrol());
        rolUsuarioImpl.setNombrerol(getNombrerol());

        rolUsuarioImpl.resetOriginalValues();

        return rolUsuarioImpl;
    }

    @Override
    public int compareTo(RolUsuario rolUsuario) {
        int primaryKey = rolUsuario.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof RolUsuario)) {
            return false;
        }

        RolUsuario rolUsuario = (RolUsuario) obj;

        int primaryKey = rolUsuario.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
    }

    @Override
    public CacheModel<RolUsuario> toCacheModel() {
        RolUsuarioCacheModel rolUsuarioCacheModel = new RolUsuarioCacheModel();

        rolUsuarioCacheModel.idrol = getIdrol();

        rolUsuarioCacheModel.nombrerol = getNombrerol();

        String nombrerol = rolUsuarioCacheModel.nombrerol;

        if ((nombrerol != null) && (nombrerol.length() == 0)) {
            rolUsuarioCacheModel.nombrerol = null;
        }

        return rolUsuarioCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(5);

        sb.append("{idrol=");
        sb.append(getIdrol());
        sb.append(", nombrerol=");
        sb.append(getNombrerol());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(10);

        sb.append("<model><model-name>");
        sb.append("com.telefonica.centroseducativos.model.RolUsuario");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>idrol</column-name><column-value><![CDATA[");
        sb.append(getIdrol());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>nombrerol</column-name><column-value><![CDATA[");
        sb.append(getNombrerol());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
