package com.telefonica.centroseducativos.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.telefonica.centroseducativos.model.CentroEducativo;
import com.telefonica.centroseducativos.service.CentroEducativoLocalServiceUtil;

/**
 * The extended model base implementation for the CentroEducativo service. Represents a row in the &quot;CentrosEducativos_CentroEducativo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CentroEducativoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CentroEducativoImpl
 * @see com.telefonica.centroseducativos.model.CentroEducativo
 * @generated
 */
public abstract class CentroEducativoBaseImpl extends CentroEducativoModelImpl
    implements CentroEducativo {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a centro educativo model instance should use the {@link CentroEducativo} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            CentroEducativoLocalServiceUtil.addCentroEducativo(this);
        } else {
            CentroEducativoLocalServiceUtil.updateCentroEducativo(this);
        }
    }
}
