package com.telefonica.centroseducativos.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.telefonica.centroseducativos.model.ComunidadAutonoma;
import com.telefonica.centroseducativos.service.ComunidadAutonomaLocalServiceUtil;

/**
 * The extended model base implementation for the ComunidadAutonoma service. Represents a row in the &quot;CentrosEducativos_ComunidadAutonoma&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ComunidadAutonomaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ComunidadAutonomaImpl
 * @see com.telefonica.centroseducativos.model.ComunidadAutonoma
 * @generated
 */
public abstract class ComunidadAutonomaBaseImpl
    extends ComunidadAutonomaModelImpl implements ComunidadAutonoma {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a comunidad autonoma model instance should use the {@link ComunidadAutonoma} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            ComunidadAutonomaLocalServiceUtil.addComunidadAutonoma(this);
        } else {
            ComunidadAutonomaLocalServiceUtil.updateComunidadAutonoma(this);
        }
    }
}
