package com.telefonica.centroseducativos.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.telefonica.centroseducativos.model.EvaluacionesCE;
import com.telefonica.centroseducativos.service.EvaluacionesCELocalServiceUtil;

/**
 * The extended model base implementation for the EvaluacionesCE service. Represents a row in the &quot;CentrosEducativos_EvaluacionesCE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EvaluacionesCEImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EvaluacionesCEImpl
 * @see com.telefonica.centroseducativos.model.EvaluacionesCE
 * @generated
 */
public abstract class EvaluacionesCEBaseImpl extends EvaluacionesCEModelImpl
    implements EvaluacionesCE {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a evaluaciones c e model instance should use the {@link EvaluacionesCE} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            EvaluacionesCELocalServiceUtil.addEvaluacionesCE(this);
        } else {
            EvaluacionesCELocalServiceUtil.updateEvaluacionesCE(this);
        }
    }
}
