package com.telefonica.centroseducativos.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.telefonica.centroseducativos.model.RolUsuario;
import com.telefonica.centroseducativos.service.RolUsuarioLocalServiceUtil;

/**
 * The extended model base implementation for the RolUsuario service. Represents a row in the &quot;CentrosEducativos_RolUsuario&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RolUsuarioImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RolUsuarioImpl
 * @see com.telefonica.centroseducativos.model.RolUsuario
 * @generated
 */
public abstract class RolUsuarioBaseImpl extends RolUsuarioModelImpl
    implements RolUsuario {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a rol usuario model instance should use the {@link RolUsuario} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            RolUsuarioLocalServiceUtil.addRolUsuario(this);
        } else {
            RolUsuarioLocalServiceUtil.updateRolUsuario(this);
        }
    }
}
