package com.telefonica.centroseducativos.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import com.telefonica.centroseducativos.service.persistence.EvaluacionesCEPK;

import java.io.Serializable;

/**
 * The base model interface for the EvaluacionesCE service. Represents a row in the &quot;CentrosEducativos_EvaluacionesCE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.telefonica.centroseducativos.model.impl.EvaluacionesCEModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.telefonica.centroseducativos.model.impl.EvaluacionesCEImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EvaluacionesCE
 * @see com.telefonica.centroseducativos.model.impl.EvaluacionesCEImpl
 * @see com.telefonica.centroseducativos.model.impl.EvaluacionesCEModelImpl
 * @generated
 */
public interface EvaluacionesCEModel extends BaseModel<EvaluacionesCE> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a evaluaciones c e model instance should use the {@link EvaluacionesCE} interface instead.
     */

    /**
     * Returns the primary key of this evaluaciones c e.
     *
     * @return the primary key of this evaluaciones c e
     */
    public EvaluacionesCEPK getPrimaryKey();

    /**
     * Sets the primary key of this evaluaciones c e.
     *
     * @param primaryKey the primary key of this evaluaciones c e
     */
    public void setPrimaryKey(EvaluacionesCEPK primaryKey);

    /**
     * Returns the idencuesta of this evaluaciones c e.
     *
     * @return the idencuesta of this evaluaciones c e
     */
    public int getIdencuesta();

    /**
     * Sets the idencuesta of this evaluaciones c e.
     *
     * @param idencuesta the idencuesta of this evaluaciones c e
     */
    public void setIdencuesta(int idencuesta);

    /**
     * Returns the numpregunta of this evaluaciones c e.
     *
     * @return the numpregunta of this evaluaciones c e
     */
    public int getNumpregunta();

    /**
     * Sets the numpregunta of this evaluaciones c e.
     *
     * @param numpregunta the numpregunta of this evaluaciones c e
     */
    public void setNumpregunta(int numpregunta);

    /**
     * Returns the notapregunta of this evaluaciones c e.
     *
     * @return the notapregunta of this evaluaciones c e
     */
    public int getNotapregunta();

    /**
     * Sets the notapregunta of this evaluaciones c e.
     *
     * @param notapregunta the notapregunta of this evaluaciones c e
     */
    public void setNotapregunta(int notapregunta);

    /**
     * Returns the idce of this evaluaciones c e.
     *
     * @return the idce of this evaluaciones c e
     */
    public int getIdce();

    /**
     * Sets the idce of this evaluaciones c e.
     *
     * @param idce the idce of this evaluaciones c e
     */
    public void setIdce(int idce);

    /**
     * Returns the idrol of this evaluaciones c e.
     *
     * @return the idrol of this evaluaciones c e
     */
    public int getIdrol();

    /**
     * Sets the idrol of this evaluaciones c e.
     *
     * @param idrol the idrol of this evaluaciones c e
     */
    public void setIdrol(int idrol);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        com.telefonica.centroseducativos.model.EvaluacionesCE evaluacionesCE);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.telefonica.centroseducativos.model.EvaluacionesCE> toCacheModel();

    @Override
    public com.telefonica.centroseducativos.model.EvaluacionesCE toEscapedModel();

    @Override
    public com.telefonica.centroseducativos.model.EvaluacionesCE toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
