package com.telefonica.centroseducativos.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Pais service. Represents a row in the &quot;CentrosEducativos_Pais&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.telefonica.centroseducativos.model.impl.PaisModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.telefonica.centroseducativos.model.impl.PaisImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Pais
 * @see com.telefonica.centroseducativos.model.impl.PaisImpl
 * @see com.telefonica.centroseducativos.model.impl.PaisModelImpl
 * @generated
 */
public interface PaisModel extends BaseModel<Pais> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a pais model instance should use the {@link Pais} interface instead.
     */

    /**
     * Returns the primary key of this pais.
     *
     * @return the primary key of this pais
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this pais.
     *
     * @param primaryKey the primary key of this pais
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the idpais of this pais.
     *
     * @return the idpais of this pais
     */
    public int getIdpais();

    /**
     * Sets the idpais of this pais.
     *
     * @param idpais the idpais of this pais
     */
    public void setIdpais(int idpais);

    /**
     * Returns the nombrepais of this pais.
     *
     * @return the nombrepais of this pais
     */
    @AutoEscape
    public String getNombrepais();

    /**
     * Sets the nombrepais of this pais.
     *
     * @param nombrepais the nombrepais of this pais
     */
    public void setNombrepais(String nombrepais);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.telefonica.centroseducativos.model.Pais pais);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.telefonica.centroseducativos.model.Pais> toCacheModel();

    @Override
    public com.telefonica.centroseducativos.model.Pais toEscapedModel();

    @Override
    public com.telefonica.centroseducativos.model.Pais toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
