package com.telefonica.centroseducativos.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the PreguntasEncuesta service. Represents a row in the &quot;CentrosEducativos_PreguntasEncuesta&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.telefonica.centroseducativos.model.impl.PreguntasEncuestaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.telefonica.centroseducativos.model.impl.PreguntasEncuestaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PreguntasEncuesta
 * @see com.telefonica.centroseducativos.model.impl.PreguntasEncuestaImpl
 * @see com.telefonica.centroseducativos.model.impl.PreguntasEncuestaModelImpl
 * @generated
 */
public interface PreguntasEncuestaModel extends BaseModel<PreguntasEncuesta> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a preguntas encuesta model instance should use the {@link PreguntasEncuesta} interface instead.
     */

    /**
     * Returns the primary key of this preguntas encuesta.
     *
     * @return the primary key of this preguntas encuesta
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this preguntas encuesta.
     *
     * @param primaryKey the primary key of this preguntas encuesta
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the numpregunta of this preguntas encuesta.
     *
     * @return the numpregunta of this preguntas encuesta
     */
    public int getNumpregunta();

    /**
     * Sets the numpregunta of this preguntas encuesta.
     *
     * @param numpregunta the numpregunta of this preguntas encuesta
     */
    public void setNumpregunta(int numpregunta);

    /**
     * Returns the enunciadopregunta of this preguntas encuesta.
     *
     * @return the enunciadopregunta of this preguntas encuesta
     */
    @AutoEscape
    public String getEnunciadopregunta();

    /**
     * Sets the enunciadopregunta of this preguntas encuesta.
     *
     * @param enunciadopregunta the enunciadopregunta of this preguntas encuesta
     */
    public void setEnunciadopregunta(String enunciadopregunta);

    /**
     * Returns the idcategoria of this preguntas encuesta.
     *
     * @return the idcategoria of this preguntas encuesta
     */
    public long getIdcategoria();

    /**
     * Sets the idcategoria of this preguntas encuesta.
     *
     * @param idcategoria the idcategoria of this preguntas encuesta
     */
    public void setIdcategoria(long idcategoria);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        com.telefonica.centroseducativos.model.PreguntasEncuesta preguntasEncuesta);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.telefonica.centroseducativos.model.PreguntasEncuesta> toCacheModel();

    @Override
    public com.telefonica.centroseducativos.model.PreguntasEncuesta toEscapedModel();

    @Override
    public com.telefonica.centroseducativos.model.PreguntasEncuesta toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
